### ISSUE TITLE
How to build for browserify?

### ISSUE THREAD

**Issue by tiltmine** [ngokevin/pokery#2]
Hello, I am trying to build a version of pokery for the browser but am struggling with browserify.

My *main.js* looks like this:

```
import Range from 'pokery';
console.log(new Range('AQ').hands);
```

I've tried:
`` browserify main.js -o bundle.js ``

But received the following:

```
main.js:2
import Range from 'pokery';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module
```

So, I then tried:

``browserify main.js  -g [ babelify --presets [ "es2015" ] ] -o bundle.js``

This successfully compiles bundle.js but when I include it in an HTML file I get:

```
Uncaught TypeError: ranges.map is not a function
    at new Simulator (bundle.js:12864)
    at Object.9.pokery (bundle.js:13122)
    at o (bundle.js:1)
    at r (bundle.js:1)
    at bundle.js:1
```

I apologize if this is obvious!!! 

I was also thinking it might be helpful to include an already built version of pokery that users could just include from a normal html file and play around with!

**Comment by ngokevin** [comment]
Hey, thanks for the interest in this project! You might need like stage0 preset since it uses some ES6+ features.

**Comment by tiltmine** [comment]
@ngokevin thanks Kevin :)
